version: 2.1
orbs:
    codecov: codecov/codecov@1.0.5
workflows:
    test:
        jobs:
            - test-latest
            - test-dubnium
            - test-carbon
jobs:
    test-latest:
        docker:
            - image: circleci/node:latest
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn cache clean
            - run: yarn install
            - run: yarn test:cov
            - run: yarn run build
            - codecov/upload:
                  file: /home/circleci/repo/coverage/lcov.info
            - codecov/upload:
                  file: /home/circleci/repo/coverage/clover.xml
    test-carbon:
        docker:
            - image: circleci/node:carbon
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn cache clean
            - run: yarn install
            - run: yarn test:ci
            - run: yarn run build
    test-dubnium:
        docker:
            - image: circleci/node:dubnium
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn cache clean
            - run: yarn install
            - run: yarn test:ci
            - run: yarn run build
